spring:
  application:
    name: haze-ai-hub
  profiles:
    active: dev
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${ai.bailian.api-key}
      chat:
        options:
          model: deepseek-r1
          temperature: 0.8
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    top.hazenix.hazeaihub: debug

