spring:
  application:
    name: haze-ai-hub
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${ai.bailian.api-key}
      chat:
        options:
          model: deepseek-v3.2
          temperature: 0.8

